### ISSUE TITLE
No Service

### ISSUE THREAD

**Issue by grantmacken** [eXist-db/existdb-packageservice#1]
Just tried, but got 
```
<repo-response><fail>no service</fail></repo-response>  
```
Stopped and restarted eXist and got same again. 

Using  
- existdb-packageservice Version: 0.37.1 
- latest eXist release version 3.5.0
-  latest Firefox version 57

**Comment by JoernT** [comment]
this is actually expected behavior. The packageservice is an headless app to be used by other apps like existdb-packagemanager and the upcoming new existdb-dashboard.

Maybe should present a more friendly message to annouce that. Proposals?

**Comment by dizzzz** [comment]
@JoernT why not have it installed as a library-app ?

**Comment by JoernT** [comment]
i've added a proper error page for the service now.
